[settings]
timeout = 2000
node_verifier = "None"

[relaychain]
default_command = "./bin/polkadot"
default_args = ["-lparachain=debug", "-lxcm=trace", "-lruntime=debug"]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  [[relaychain.nodes]]
  name = "charlie"
  validator = true

  [[relaychain.nodes]]
  name = "dave"
  validator = true

[[parachains]]
id = 1000
cumulus_based = true

  [[parachains.collators]]
  name = "assethub-collator"
  command = "./bin/polkadot-parachain"
  args = ["-lxcmp=trace", "-lxcm=trace", "-lruntime=debug"]
  ws_port = 9999

[[parachains]]
id = 4607
cumulus_based = true

  [[parachains.collators]]
  name = "xode-collator"
  command = "../target/release/xode-node"
  args = ["-lxcmp=trace", "-lxcm=trace", "-lruntime=debug"]
  ws_port = 9999